project:
  type: website
  # output-dir: docs
  render:
    - "!homework/*"
    - "*.qmd"

website:
  title: "SR3TuringQuarto.jl"
  page-footer: "☕️ made with ❤️ by danton." 
  navbar:
    search: true
    tools:
      - icon: globe
        url: http://danton.codes
      - icon: github
        text: Source
        url: https://github.com/dantonnoriega/SR3TuringQuarto.jl
    left:
      - text: "Home"
        file: index.qmd
      - text: "Notebooks"
        file: notebooks.qmd

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css